using Microsoft.EntityFrameworkCore;
using ProyectoMerck.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProyectoMerck.DataAccess.DatabaseSeeding
{
    public class LocationSeeder : IEntitySeeder
    {
        public void SeedDataBase(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Location>().HasData(
                new Location { Id = 1, ProvinceId = 1, LocationName = "25 de Mayo" },
                new Location { Id = 2, ProvinceId = 1, LocationName = "3 de febrero" },
                new Location { Id = 3, ProvinceId = 1, LocationName = "A. Alsina" },
                new Location { Id = 4, ProvinceId = 1, LocationName = "A. Gonzáles Cháves" },
                new Location { Id = 5, ProvinceId = 1, LocationName = "Aguas Verdes" },
                new Location { Id = 6, ProvinceId = 1, LocationName = "Alberti" },
                new Location { Id = 7, ProvinceId = 1, LocationName = "Arrecifes" },
                new Location { Id = 8, ProvinceId = 1, LocationName = "Ayacucho" },
                new Location { Id = 9, ProvinceId = 1, LocationName = "Azul" },
                new Location { Id = 10, ProvinceId = 1, LocationName = "Bahía Blanca" },
                new Location { Id = 11, ProvinceId = 1, LocationName = "Balcarce" },
                new Location { Id = 12, ProvinceId = 1, LocationName = "Baradero" },
                new Location { Id = 13, ProvinceId = 1, LocationName = "Benito Juárez" },
                new Location { Id = 14, ProvinceId = 1, LocationName = "Berisso" },
                new Location { Id = 15, ProvinceId = 1, LocationName = "Bolívar" },
                new Location { Id = 16, ProvinceId = 1, LocationName = "Bragado" },
                new Location { Id = 17, ProvinceId = 1, LocationName = "Brandsen" },
                new Location { Id = 18, ProvinceId = 1, LocationName = "Campana" },
                new Location { Id = 19, ProvinceId = 1, LocationName = "Cañuelas" },
                new Location { Id = 20, ProvinceId = 1, LocationName = "Capilla del Señor" },
                new Location { Id = 21, ProvinceId = 1, LocationName = "Capitán Sarmiento" },
                new Location { Id = 22, ProvinceId = 1, LocationName = "Carapachay" },
                new Location { Id = 23, ProvinceId = 1, LocationName = "Carhue" },
                new Location { Id = 24, ProvinceId = 1, LocationName = "Cariló" },
                new Location { Id = 25, ProvinceId = 1, LocationName = "Carlos Casares" },
                new Location { Id = 26, ProvinceId = 1, LocationName = "Carlos Tejedor" },
                new Location { Id = 27, ProvinceId = 1, LocationName = "Carmen de Areco" },
                new Location { Id = 28, ProvinceId = 1, LocationName = "Carmen de Patagones" },
                new Location { Id = 29, ProvinceId = 1, LocationName = "Castelli" },
                new Location { Id = 30, ProvinceId = 1, LocationName = "Chacabuco" },
                new Location { Id = 31, ProvinceId = 1, LocationName = "Chascomús" },
                new Location { Id = 32, ProvinceId = 1, LocationName = "Chivilcoy" },
                new Location { Id = 33, ProvinceId = 1, LocationName = "Colón" },
                new Location { Id = 34, ProvinceId = 1, LocationName = "Coronel Dorrego" },
                new Location { Id = 35, ProvinceId = 1, LocationName = "Coronel Pringles" },
                new Location { Id = 36, ProvinceId = 1, LocationName = "Coronel Rosales" },
                new Location { Id = 37, ProvinceId = 1, LocationName = "Coronel Suarez" },
                new Location { Id = 38, ProvinceId = 1, LocationName = "Costa Azul" },
                new Location { Id = 39, ProvinceId = 1, LocationName = "Costa Chica" },
                new Location { Id = 40, ProvinceId = 1, LocationName = "Costa del Este" },
                new Location { Id = 41, ProvinceId = 1, LocationName = "Costa Esmeralda" },
                new Location { Id = 42, ProvinceId = 1, LocationName = "Daireaux" },
                new Location { Id = 43, ProvinceId = 1, LocationName = "Darregueira" },
                new Location { Id = 44, ProvinceId = 1, LocationName = "Del Viso" },
                new Location { Id = 45, ProvinceId = 1, LocationName = "Dolores" },
                new Location { Id = 46, ProvinceId = 1, LocationName = "Don Torcuato" },
                new Location { Id = 47, ProvinceId = 1, LocationName = "Ensenada" },
                new Location { Id = 48, ProvinceId = 1, LocationName = "Escobar" },
                new Location { Id = 49, ProvinceId = 1, LocationName = "Exaltación de la Cruz" },
                new Location { Id = 50, ProvinceId = 1, LocationName = "Florentino Ameghino" },
                new Location { Id = 282, ProvinceId = 3, LocationName = "Agronomía" },
                new Location { Id = 283, ProvinceId = 3, LocationName = "Almagro" },
                new Location { Id = 284, ProvinceId = 3, LocationName = "Balvanera" },
                new Location { Id = 285, ProvinceId = 3, LocationName = "Barracas" },
                new Location { Id = 286, ProvinceId = 3, LocationName = "Belgrano" },
                new Location { Id = 287, ProvinceId = 3, LocationName = "Boca" },
                new Location { Id = 288, ProvinceId = 3, LocationName = "Boedo" },
                new Location { Id = 289, ProvinceId = 3, LocationName = "Caballito" },
                new Location { Id = 290, ProvinceId = 3, LocationName = "Chacarita" },
                new Location { Id = 291, ProvinceId = 3, LocationName = "Coghlan" },
                new Location { Id = 292, ProvinceId = 3, LocationName = "Colegiales" },
                new Location { Id = 293, ProvinceId = 3, LocationName = "Constitución" },
                new Location { Id = 294, ProvinceId = 3, LocationName = "Flores" },
                new Location { Id = 295, ProvinceId = 3, LocationName = "Floresta" },
                new Location { Id = 296, ProvinceId = 3, LocationName = "La Paternal" },
                new Location { Id = 297, ProvinceId = 3, LocationName = "Liniers" },
                new Location { Id = 298, ProvinceId = 3, LocationName = "Mataderos" },
                new Location { Id = 299, ProvinceId = 3, LocationName = "Monserrat" },
                new Location { Id = 300, ProvinceId = 3, LocationName = "Monte Castro" },
                new Location { Id = 301, ProvinceId = 3, LocationName = "Nueva Pompeya" },
                new Location { Id = 302, ProvinceId = 3, LocationName = "Núñez" },
                new Location { Id = 303, ProvinceId = 3, LocationName = "Palermo" },
                new Location { Id = 304, ProvinceId = 3, LocationName = "Parque Avellaneda" },
                new Location { Id = 305, ProvinceId = 3, LocationName = "Parque Chacabuco" },
                new Location { Id = 306, ProvinceId = 3, LocationName = "Parque Chas" },
                new Location { Id = 307, ProvinceId = 3, LocationName = "Parque Patricios" },
                new Location { Id = 308, ProvinceId = 3, LocationName = "Puerto Madero" },
                new Location { Id = 309, ProvinceId = 3, LocationName = "Recoleta" },
                new Location { Id = 310, ProvinceId = 3, LocationName = "Retiro" },
                new Location { Id = 311, ProvinceId = 3, LocationName = "Saavedra" },
                new Location { Id = 312, ProvinceId = 3, LocationName = "San Cristóbal" },
                new Location { Id = 313, ProvinceId = 3, LocationName = "San Nicolás" },
                new Location { Id = 314, ProvinceId = 3, LocationName = "San Telmo" },
                new Location { Id = 315, ProvinceId = 3, LocationName = "Vélez Sársfield" },
                new Location { Id = 316, ProvinceId = 3, LocationName = "Versalles" },
                new Location { Id = 317, ProvinceId = 3, LocationName = "Villa Crespo" },
                new Location { Id = 318, ProvinceId = 3, LocationName = "Villa del Parque" },
                new Location { Id = 319, ProvinceId = 3, LocationName = "Villa Devoto" },
                new Location { Id = 320, ProvinceId = 3, LocationName = "Villa Gral. Mitre" },
                new Location { Id = 321, ProvinceId = 3, LocationName = "Villa Lugano" },
                new Location { Id = 322, ProvinceId = 3, LocationName = "Villa Luro" },
                new Location { Id = 323, ProvinceId = 3, LocationName = "Villa Ortúzar" },
                new Location { Id = 324, ProvinceId = 3, LocationName = "Villa Pueyrredón" },
                new Location { Id = 325, ProvinceId = 3, LocationName = "Villa Real" },
                new Location { Id = 326, ProvinceId = 3, LocationName = "Villa Riachuelo" },
                new Location { Id = 327, ProvinceId = 3, LocationName = "Villa Santa Rita" },
                new Location { Id = 328, ProvinceId = 3, LocationName = "Villa Soldati" },
                new Location { Id = 329, ProvinceId = 3, LocationName = "Villa Urquiza" },
                new Location { Id = 330, ProvinceId = 4, LocationName = "Aconquija" },
                new Location { Id = 331, ProvinceId = 4, LocationName = "Ancasti" },
                new Location { Id = 332, ProvinceId = 4, LocationName = "Andalgalá" },
                new Location { Id = 333, ProvinceId = 4, LocationName = "Antofagasta" },
                new Location { Id = 334, ProvinceId = 4, LocationName = "Belén" },
                new Location { Id = 335, ProvinceId = 4, LocationName = "Capayán" },
                new Location { Id = 336, ProvinceId = 4, LocationName = "Capital" },
                new Location { Id = 337, ProvinceId = 4, LocationName = "4" },
                new Location { Id = 338, ProvinceId = 4, LocationName = "Corral Quemado" },
                new Location { Id = 339, ProvinceId = 4, LocationName = "El Alto" },
                new Location { Id = 340, ProvinceId = 4, LocationName = "El Rodeo" },
                new Location { Id = 341, ProvinceId = 4, LocationName = "F.Mamerto Esquiú" },
                new Location { Id = 342, ProvinceId = 4, LocationName = "Fiambalá" },
                new Location { Id = 343, ProvinceId = 4, LocationName = "Hualfín" },
                new Location { Id = 344, ProvinceId = 4, LocationName = "Huillapima" },
                new Location { Id = 345, ProvinceId = 4, LocationName = "Icaño" },
                new Location { Id = 346, ProvinceId = 4, LocationName = "La Puerta" },
                new Location { Id = 347, ProvinceId = 4, LocationName = "Las Juntas" },
                new Location { Id = 348, ProvinceId = 4, LocationName = "Londres" },
                new Location { Id = 381, ProvinceId = 5, LocationName = "Col. Elisa" },
                new Location { Id = 382, ProvinceId = 5, LocationName = "Col. Popular" },
                new Location { Id = 383, ProvinceId = 5, LocationName = "Colonias Unidas" },
                new Location { Id = 384, ProvinceId = 5, LocationName = "Concepción" },
                new Location { Id = 385, ProvinceId = 5, LocationName = "Corzuela" },
                new Location { Id = 386, ProvinceId = 5, LocationName = "Cote Lai" },
                new Location { Id = 387, ProvinceId = 5, LocationName = "El Sauzalito" },
                new Location { Id = 388, ProvinceId = 5, LocationName = "Enrique Urien" },
                new Location { Id = 389, ProvinceId = 5, LocationName = "Fontana" },
                new Location { Id = 390, ProvinceId = 5, LocationName = "Fte. Esperanza" },
                new Location { Id = 391, ProvinceId = 5, LocationName = "Gancedo" },
                new Location { Id = 392, ProvinceId = 5, LocationName = "Gral. Capdevila" },
                new Location { Id = 393, ProvinceId = 5, LocationName = "Gral. Pinero" },
                new Location { Id = 394, ProvinceId = 5, LocationName = "Gral. San Martín" },
                new Location { Id = 395, ProvinceId = 5, LocationName = "Gral. Vedia" },
                new Location { Id = 396, ProvinceId = 5, LocationName = "Hermoso Campo" },
                new Location { Id = 397, ProvinceId = 5, LocationName = "I. del Cerrito" },
                new Location { Id = 398, ProvinceId = 5, LocationName = "J.J. Castelli" },
                new Location { Id = 399, ProvinceId = 5, LocationName = "La Clotilde" },
                new Location { Id = 400, ProvinceId = 5, LocationName = "La Eduvigis" },
                new Location { Id = 401, ProvinceId = 5, LocationName = "La Escondida" },
                new Location { Id = 402, ProvinceId = 5, LocationName = "La Leonesa" },
                new Location { Id = 403, ProvinceId = 5, LocationName = "La Tigra" },
                new Location { Id = 404, ProvinceId = 5, LocationName = "La Verde" },
                new Location { Id = 453, ProvinceId = 6, LocationName = "Dolavón" },
                new Location { Id = 454, ProvinceId = 6, LocationName = "Dr. R. Rojas" },
                new Location { Id = 455, ProvinceId = 6, LocationName = "El Hoyo" },
                new Location { Id = 456, ProvinceId = 6, LocationName = "El Maitén" },
                new Location { Id = 457, ProvinceId = 6, LocationName = "Epuyén" },
                new Location { Id = 458, ProvinceId = 6, LocationName = "Esquel" },
                new Location { Id = 459, ProvinceId = 6, LocationName = "Facundo" },
                new Location { Id = 460, ProvinceId = 6, LocationName = "Gaimán" },
                new Location { Id = 461, ProvinceId = 6, LocationName = "Gan Gan" },
                new Location { Id = 462, ProvinceId = 6, LocationName = "Gastre" },
                new Location { Id = 463, ProvinceId = 6, LocationName = "Gdor. Costa" },
                new Location { Id = 464, ProvinceId = 6, LocationName = "Gualjaina" },
                new Location { Id = 465, ProvinceId = 6, LocationName = "J. de San Martín" },
                new Location { Id = 466, ProvinceId = 6, LocationName = "Lago Blanco" },
                new Location { Id = 467, ProvinceId = 6, LocationName = "Lago Puelo" },
                new Location { Id = 468, ProvinceId = 6, LocationName = "Lagunita Salada" },
                new Location { Id = 469, ProvinceId = 6, LocationName = "Las Plumas" },
                new Location { Id = 470, ProvinceId = 6, LocationName = "Los Altares" },
                new Location { Id = 504, ProvinceId = 7, LocationName = "Arias" },
                new Location { Id = 505, ProvinceId = 7, LocationName = "Arroyito" },
                new Location { Id = 506, ProvinceId = 7, LocationName = "Arroyo Algodon" },
                new Location { Id = 507, ProvinceId = 7, LocationName = "Arroyo Cabral" },
                new Location { Id = 508, ProvinceId = 7, LocationName = "Arroyo Los Patos" },
                new Location { Id = 509, ProvinceId = 7, LocationName = "Assunta" },
                new Location { Id = 510, ProvinceId = 7, LocationName = "Atahona" },
                new Location { Id = 511, ProvinceId = 7, LocationName = "Ausonia" },
                new Location { Id = 512, ProvinceId = 7, LocationName = "Avellaneda" },
                new Location { Id = 513, ProvinceId = 7, LocationName = "Ballesteros" },
                new Location { Id = 514, ProvinceId = 7, LocationName = "Ballesteros Sud" },
                new Location { Id = 515, ProvinceId = 7, LocationName = "Balnearia" },
                new Location { Id = 516, ProvinceId = 7, LocationName = "Bañado de Soto" },
                new Location { Id = 517, ProvinceId = 7, LocationName = "Bell Ville" },
                new Location { Id = 518, ProvinceId = 7, LocationName = "Bengolea" },
                new Location { Id = 519, ProvinceId = 7, LocationName = "Benjamin Gould" },
                new Location { Id = 520, ProvinceId = 7, LocationName = "Berrotaran" },
                new Location { Id = 521, ProvinceId = 7, LocationName = "Bialet Masse" },
                new Location { Id = 522, ProvinceId = 7, LocationName = "Bouwer" },
                new Location { Id = 523, ProvinceId = 7, LocationName = "Brinkmann" },
                new Location { Id = 524, ProvinceId = 7, LocationName = "Buchardo" },
                new Location { Id = 525, ProvinceId = 7, LocationName = "Bulnes" },
                new Location { Id = 526, ProvinceId = 7, LocationName = "Cabalango" },
                new Location { Id = 527, ProvinceId = 7, LocationName = "Calamuchita" },
                new Location { Id = 963, ProvinceId = 8, LocationName = "Saladas" },
                new Location { Id = 964, ProvinceId = 8, LocationName = "San Antonio" }
                );
        }
    }
}
