// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Merck.Areas.Identity.Data;

#nullable disable

namespace ProyectoMerck.DataAccess.Migrations
{
    [DbContext(typeof(AppMerckContext))]
    [Migration("20240222200028_fixer")]
    partial class fixer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProyectoMerck.Models.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Viamonte 1432",
                            ClinicName = "CEGYR Medicina Reproductiva",
                            Latitude = -34.6007441,
                            Length = -58.387174100000003,
                            ProvinceId = 3,
                            ProvinceName = "Capital Federal"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Humboldt 2263",
                            ClinicName = "CER",
                            Latitude = -34.5806714,
                            Length = -58.4302438,
                            ProvinceId = 4,
                            ProvinceName = "Catamarca"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Av.Forest 1166",
                            ClinicName = "Centro de Investigaciones en Medicina Reproductiva",
                            Latitude = -34.578822199999998,
                            Length = -58.460096700000001,
                            ProvinceId = 4,
                            ProvinceName = "Chaco"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Alvear 514",
                            ClinicName = "Centro Gens",
                            Latitude = -34.7197709,
                            Length = -58.256260400000002,
                            ProvinceId = 5,
                            ProvinceName = "Chubut"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Marcelo T. de Alvear 2084",
                            ClinicName = "Halitus Instituto Médico",
                            Latitude = -34.597464299999999,
                            Length = -58.3971746,
                            ProvinceId = 3,
                            ProvinceName = "Capital Federal"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Bulnes 1104",
                            ClinicName = "Maternity Bank",
                            Latitude = -34.598300000000002,
                            Length = -58.417900000000003,
                            ProvinceId = 3,
                            ProvinceName = "Capital Federal"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Av. del Libertador 5962",
                            ClinicName = "WeFIV",
                            Latitude = -34.557099999999998,
                            Length = -58.447600000000001,
                            ProvinceId = 3,
                            ProvinceName = "Capital Federal"
                        });
                });

            modelBuilder.Entity("ProyectoMerck.Models.Entities.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clinic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsultationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAndtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clinic = "CEGYR Medicina Reproductiva",
                            ConsultationReason = "Edad y Reserva Ovarica",
                            DateAndtime = new DateTime(2024, 2, 22, 17, 0, 28, 457, DateTimeKind.Local).AddTicks(3644),
                            Url = "https://ejemplo.com/"
                        },
                        new
                        {
                            Id = 2,
                            Clinic = "Centro de Investigaciones en Medicina Reproductiva",
                            ConsultationReason = "Evaluación de Reserva Ovárica",
                            DateAndtime = new DateTime(2024, 2, 22, 17, 0, 28, 457, DateTimeKind.Local).AddTicks(3736),
                            Url = "https://ejemplo2.com/"
                        });
                });

            modelBuilder.Entity("ProyectoMerck.Models.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Argentina"
                        });
                });

            modelBuilder.Entity("ProyectoMerck.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationName = "25 de Mayo",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            LocationName = "3 de febrero",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            LocationName = "A. Alsina",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            LocationName = "A. Gonzáles Cháves",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 5,
                            LocationName = "Aguas Verdes",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 6,
                            LocationName = "Alberti",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 7,
                            LocationName = "Arrecifes",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 8,
                            LocationName = "Ayacucho",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 9,
                            LocationName = "Azul",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 10,
                            LocationName = "Bahía Blanca",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 11,
                            LocationName = "Balcarce",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 12,
                            LocationName = "Baradero",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 13,
                            LocationName = "Benito Juárez",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 14,
                            LocationName = "Berisso",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 15,
                            LocationName = "Bolívar",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 16,
                            LocationName = "Bragado",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 17,
                            LocationName = "Brandsen",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 18,
                            LocationName = "Campana",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 19,
                            LocationName = "Cañuelas",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 20,
                            LocationName = "Capilla del Señor",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 21,
                            LocationName = "Capitán Sarmiento",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 22,
                            LocationName = "Carapachay",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 23,
                            LocationName = "Carhue",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 24,
                            LocationName = "Cariló",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 25,
                            LocationName = "Carlos Casares",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 26,
                            LocationName = "Carlos Tejedor",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 27,
                            LocationName = "Carmen de Areco",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 28,
                            LocationName = "Carmen de Patagones",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 29,
                            LocationName = "Castelli",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 30,
                            LocationName = "Chacabuco",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 31,
                            LocationName = "Chascomús",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 32,
                            LocationName = "Chivilcoy",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 33,
                            LocationName = "Colón",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 34,
                            LocationName = "Coronel Dorrego",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 35,
                            LocationName = "Coronel Pringles",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 36,
                            LocationName = "Coronel Rosales",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 37,
                            LocationName = "Coronel Suarez",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 38,
                            LocationName = "Costa Azul",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 39,
                            LocationName = "Costa Chica",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 40,
                            LocationName = "Costa del Este",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 41,
                            LocationName = "Costa Esmeralda",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 42,
                            LocationName = "Daireaux",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 43,
                            LocationName = "Darregueira",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 44,
                            LocationName = "Del Viso",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 45,
                            LocationName = "Dolores",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 46,
                            LocationName = "Don Torcuato",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 47,
                            LocationName = "Ensenada",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 48,
                            LocationName = "Escobar",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 49,
                            LocationName = "Exaltación de la Cruz",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 50,
                            LocationName = "Florentino Ameghino",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 282,
                            LocationName = "Agronomía",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 283,
                            LocationName = "Almagro",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 284,
                            LocationName = "Balvanera",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 285,
                            LocationName = "Barracas",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 286,
                            LocationName = "Belgrano",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 287,
                            LocationName = "Boca",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 288,
                            LocationName = "Boedo",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 289,
                            LocationName = "Caballito",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 290,
                            LocationName = "Chacarita",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 291,
                            LocationName = "Coghlan",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 292,
                            LocationName = "Colegiales",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 293,
                            LocationName = "Constitución",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 294,
                            LocationName = "Flores",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 295,
                            LocationName = "Floresta",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 296,
                            LocationName = "La Paternal",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 297,
                            LocationName = "Liniers",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 298,
                            LocationName = "Mataderos",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 299,
                            LocationName = "Monserrat",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 300,
                            LocationName = "Monte Castro",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 301,
                            LocationName = "Nueva Pompeya",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 302,
                            LocationName = "Núñez",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 303,
                            LocationName = "Palermo",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 304,
                            LocationName = "Parque Avellaneda",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 305,
                            LocationName = "Parque Chacabuco",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 306,
                            LocationName = "Parque Chas",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 307,
                            LocationName = "Parque Patricios",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 308,
                            LocationName = "Puerto Madero",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 309,
                            LocationName = "Recoleta",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 310,
                            LocationName = "Retiro",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 311,
                            LocationName = "Saavedra",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 312,
                            LocationName = "San Cristóbal",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 313,
                            LocationName = "San Nicolás",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 314,
                            LocationName = "San Telmo",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 315,
                            LocationName = "Vélez Sársfield",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 316,
                            LocationName = "Versalles",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 317,
                            LocationName = "Villa Crespo",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 318,
                            LocationName = "Villa del Parque",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 319,
                            LocationName = "Villa Devoto",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 320,
                            LocationName = "Villa Gral. Mitre",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 321,
                            LocationName = "Villa Lugano",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 322,
                            LocationName = "Villa Luro",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 323,
                            LocationName = "Villa Ortúzar",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 324,
                            LocationName = "Villa Pueyrredón",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 325,
                            LocationName = "Villa Real",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 326,
                            LocationName = "Villa Riachuelo",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 327,
                            LocationName = "Villa Santa Rita",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 328,
                            LocationName = "Villa Soldati",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 329,
                            LocationName = "Villa Urquiza",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 330,
                            LocationName = "Aconquija",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 331,
                            LocationName = "Ancasti",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 332,
                            LocationName = "Andalgalá",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 333,
                            LocationName = "Antofagasta",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 334,
                            LocationName = "Belén",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 335,
                            LocationName = "Capayán",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 336,
                            LocationName = "Capital",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 337,
                            LocationName = "4",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 338,
                            LocationName = "Corral Quemado",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 339,
                            LocationName = "El Alto",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 340,
                            LocationName = "El Rodeo",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 341,
                            LocationName = "F.Mamerto Esquiú",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 342,
                            LocationName = "Fiambalá",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 343,
                            LocationName = "Hualfín",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 344,
                            LocationName = "Huillapima",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 345,
                            LocationName = "Icaño",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 346,
                            LocationName = "La Puerta",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 347,
                            LocationName = "Las Juntas",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 348,
                            LocationName = "Londres",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 381,
                            LocationName = "Col. Elisa",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 382,
                            LocationName = "Col. Popular",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 383,
                            LocationName = "Colonias Unidas",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 384,
                            LocationName = "Concepción",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 385,
                            LocationName = "Corzuela",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 386,
                            LocationName = "Cote Lai",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 387,
                            LocationName = "El Sauzalito",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 388,
                            LocationName = "Enrique Urien",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 389,
                            LocationName = "Fontana",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 390,
                            LocationName = "Fte. Esperanza",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 391,
                            LocationName = "Gancedo",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 392,
                            LocationName = "Gral. Capdevila",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 393,
                            LocationName = "Gral. Pinero",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 394,
                            LocationName = "Gral. San Martín",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 395,
                            LocationName = "Gral. Vedia",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 396,
                            LocationName = "Hermoso Campo",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 397,
                            LocationName = "I. del Cerrito",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 398,
                            LocationName = "J.J. Castelli",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 399,
                            LocationName = "La Clotilde",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 400,
                            LocationName = "La Eduvigis",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 401,
                            LocationName = "La Escondida",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 402,
                            LocationName = "La Leonesa",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 403,
                            LocationName = "La Tigra",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 404,
                            LocationName = "La Verde",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 453,
                            LocationName = "Dolavón",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 454,
                            LocationName = "Dr. R. Rojas",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 455,
                            LocationName = "El Hoyo",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 456,
                            LocationName = "El Maitén",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 457,
                            LocationName = "Epuyén",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 458,
                            LocationName = "Esquel",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 459,
                            LocationName = "Facundo",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 460,
                            LocationName = "Gaimán",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 461,
                            LocationName = "Gan Gan",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 462,
                            LocationName = "Gastre",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 463,
                            LocationName = "Gdor. Costa",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 464,
                            LocationName = "Gualjaina",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 465,
                            LocationName = "J. de San Martín",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 466,
                            LocationName = "Lago Blanco",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 467,
                            LocationName = "Lago Puelo",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 468,
                            LocationName = "Lagunita Salada",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 469,
                            LocationName = "Las Plumas",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 470,
                            LocationName = "Los Altares",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 504,
                            LocationName = "Arias",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 505,
                            LocationName = "Arroyito",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 506,
                            LocationName = "Arroyo Algodon",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 507,
                            LocationName = "Arroyo Cabral",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 508,
                            LocationName = "Arroyo Los Patos",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 509,
                            LocationName = "Assunta",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 510,
                            LocationName = "Atahona",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 511,
                            LocationName = "Ausonia",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 512,
                            LocationName = "Avellaneda",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 513,
                            LocationName = "Ballesteros",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 514,
                            LocationName = "Ballesteros Sud",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 515,
                            LocationName = "Balnearia",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 516,
                            LocationName = "Bañado de Soto",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 517,
                            LocationName = "Bell Ville",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 518,
                            LocationName = "Bengolea",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 519,
                            LocationName = "Benjamin Gould",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 520,
                            LocationName = "Berrotaran",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 521,
                            LocationName = "Bialet Masse",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 522,
                            LocationName = "Bouwer",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 523,
                            LocationName = "Brinkmann",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 524,
                            LocationName = "Buchardo",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 525,
                            LocationName = "Bulnes",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 526,
                            LocationName = "Cabalango",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 527,
                            LocationName = "Calamuchita",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 963,
                            LocationName = "Saladas",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 964,
                            LocationName = "San Antonio",
                            ProvinceId = 8
                        });
                });

            modelBuilder.Entity("ProyectoMerck.Models.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProvinceName = "Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            ProvinceName = "Buenos Aires-GBA"
                        },
                        new
                        {
                            Id = 3,
                            ProvinceName = "Capital Federal"
                        },
                        new
                        {
                            Id = 4,
                            ProvinceName = "Catamarca"
                        },
                        new
                        {
                            Id = 5,
                            ProvinceName = "Chaco"
                        },
                        new
                        {
                            Id = 6,
                            ProvinceName = "Chubut"
                        },
                        new
                        {
                            Id = 7,
                            ProvinceName = "Córdoba"
                        },
                        new
                        {
                            Id = 8,
                            ProvinceName = "Corrientes"
                        },
                        new
                        {
                            Id = 9,
                            ProvinceName = "Entre Ríos"
                        },
                        new
                        {
                            Id = 10,
                            ProvinceName = "Formosa"
                        },
                        new
                        {
                            Id = 11,
                            ProvinceName = "Jujuy"
                        },
                        new
                        {
                            Id = 12,
                            ProvinceName = "La Pampa"
                        },
                        new
                        {
                            Id = 13,
                            ProvinceName = "La Rioja"
                        },
                        new
                        {
                            Id = 14,
                            ProvinceName = "Mendoza"
                        },
                        new
                        {
                            Id = 15,
                            ProvinceName = "Misiones"
                        },
                        new
                        {
                            Id = 16,
                            ProvinceName = "Neuquén"
                        },
                        new
                        {
                            Id = 17,
                            ProvinceName = "Río Negro"
                        },
                        new
                        {
                            Id = 18,
                            ProvinceName = "Salta"
                        },
                        new
                        {
                            Id = 19,
                            ProvinceName = "San Juan"
                        },
                        new
                        {
                            Id = 20,
                            ProvinceName = "San Luis"
                        },
                        new
                        {
                            Id = 21,
                            ProvinceName = "Santa Cruz"
                        },
                        new
                        {
                            Id = 22,
                            ProvinceName = "Santa Fe"
                        },
                        new
                        {
                            Id = 23,
                            ProvinceName = "Santiago del Estero"
                        },
                        new
                        {
                            Id = 24,
                            ProvinceName = "Tierra del Fuego"
                        },
                        new
                        {
                            Id = 25,
                            ProvinceName = "Tucumán"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoMerck.Models.Entities.Clinic", b =>
                {
                    b.HasOne("ProyectoMerck.Models.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ProyectoMerck.Models.Entities.Location", b =>
                {
                    b.HasOne("ProyectoMerck.Models.Entities.Province", "Province")
                        .WithMany("Localities")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ProyectoMerck.Models.Entities.Province", b =>
                {
                    b.Navigation("Localities");
                });
#pragma warning restore 612, 618
        }
    }
}
